### ISSUE TITLE
Data application [clust_to_pheno.csv]

### ISSUE THREAD

**Issue by xhaoshen** [angelolab/publications#2]
Hello! Your research area interests me very much and I have benefited a lot from it. 

The problem I am currently encountering is that in your project named: 2022-Liu_Bosse_etal_CIMA project, a data named "clust_to_pheno.csv" was not found, but the data will be used in the code file named "cellClustering.R" , I wonder if it would be convenient for you to share it?

Happy new year!
Best wishes!

**Comment by xhaoshen** [comment]
<img width="776" alt="Error in fread('clust_to_pheno csv')" src="https://github.com/angelolab/publications/assets/56494904/80276978-b087-40cd-9ddf-d0153f098dfe">

**Comment by cliu72** [comment]
Answered over email, but also including the answer here:

The reason that this file wasn’t provided in the data repository is because this file will almost certainly be different for each person who runs the code. That is because the clustering algorithm that we use is stochastic, meaning that there is some amount of randomness to it. We can control this randomness by setting the seed (“set.seed()” at the top of the code), which allows us to have consistent results if we run the same code multiple times on the same machine. However, the seed is set differently for different versions of R/different machines. Therefore, running set.seed() and then doing the clustering on my machine will probably give a different result than on your machine. Therefore, the “clust_to_pheno.csv” file will likely need to be different, even if you use the same input data.

As is commented in the code in cellClustering.R (under “## 2.”), the “clust_to_pheno.csv” file should have 2 columns, ‘cluster’ with cluster numbers 1-100, and ‘phenotype’ with cell phenotypes for each cluster. These phenotypes were determined manually by looking at the heatmap. I have attached the “clust_to_pheno.csv” file that we used for our clustering [here](https://github.com/angelolab/publications/files/14015536/clust_to_pheno.csv). This mapping is the same mapping that is in the provided “cell_table_size_normalized_clusters.csv” file, in the ‘phenotype_num’ and ‘phenotype’ columns.
